/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.ArrayTable;
import com.google.common.collect.Lists;
import com.google.common.collect.Table;

import java.util.List;

public class HelloOtus {
    public static void main(String... args) {
        List<String> shopRowList = Lists.newArrayList("Shop #1", "Shop #2", "Shop #3");
        List<String> itemColumnList = Lists.newArrayList("TV Samsung", "TV LG", "TV Sony");
        Table<String, String, Integer> shopItemQuantityTable = ArrayTable.create(shopRowList, itemColumnList);

        shopItemQuantityTable.put(shopRowList.get(0), itemColumnList.get(0), 3);
        shopItemQuantityTable.put(shopRowList.get(0), itemColumnList.get(1), 10);
        shopItemQuantityTable.put(shopRowList.get(1), itemColumnList.get(2), 6);
        shopItemQuantityTable.put(shopRowList.get(2), itemColumnList.get(1), 1);
        shopItemQuantityTable.put(shopRowList.get(2), itemColumnList.get(2), 7);

        System.out.println("All shops and items: " + shopItemQuantityTable);
        System.out.println("TV LG: " + shopItemQuantityTable.column("TV LG"));
        System.out.println("Shop #1: " + shopItemQuantityTable.row("Shop #1"));

    }
}
